### ISSUE TITLE
Make it work with inline stylesheets

### ISSUE THREAD

**Issue by RandomFractals** [connor4312/vscode-css-theme-completions#1]
Example:

![image](https://user-images.githubusercontent.com/656833/97979047-23ec8300-1d94-11eb-8eaa-d9b2013c1a23.png)

Expected to see those `--vscode-` CSS completion hints there.

**Comment by connor4312** [comment]
Thanks, done in https://github.com/connor4312/vscode-css-theme-completions/commit/1a92f4d6ef17a2916f2d9e8232d4ae27568fe27e
