### ISSUE TITLE
Does it still use latest completions?

### ISSUE THREAD

**Issue by usernamehw** [connor4312/vscode-css-theme-completions#2]
Some probably recently added items are not present, like:

```
--vscode-editorSuggestWidget-selectedForeground
--vscode-editorSuggestWidget-focusHighlightForeground
```

**Comment by connor4312** [comment]
Maybe not, the function probably mysteriously stopped working at some point. However I recently have started using this for color completions in VS Code core, so I'll update this. And Martin indicated there was a better way to fetch colors without doing the shenanigans we do today.

**Comment by connor4312** [comment]
Done in https://github.com/connor4312/vscode-css-theme-completions/commit/a0a725bde5ca14f6286658e1b31f4ff2bbcef5c8. It now uses colors from your current vscode installation..
